# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb1f849a14faaf20cc3c694cb648c6d504d71538bd61bc7b61f47eca333eac163a8728db4a66090e51fcc40d117abab617fa433dd8dc831304f15d09598ae14f

test:
  secret_key_base: d4b1d7849bba075aa1199848f825dac018d3cbfd979faa032ded2aa09807391baaac4221ff4175f43d0395a91194c4aab0c2518f2b632b2dfeaa9b3e3fca541f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
